default: &default
  adapter: mysql2
  encoding: utf8
  pool: 30
  reconnect: true
  host: '127.0.0.1'
  port: '3306'
  database: 'worthy'
  username: 'root'
  password: 'annaopen'
  connect_timeout: 3


development:
  <<: *default

test:
  <<: *default
  database: 'worthy'
  password: 'annaopen'

production:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/production.sqlite3
